### ISSUE TITLE
Audit .clone() usages (especially for String); replace with references where possible

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#10]

**Comment by ilrudie** [comment]
I did a pretty simple audit of clones in 418.  It looks like we have some places where we have clones of owned values stored in different places nested within a parent data structure. This may be for legitimate reasons because in some instances the nested types are being used independently and it's not feasible to have borrows being used in this way. I didn't want to spend a lot of time potentially refactoring our types and end up with a big merge conflict so I picked some low hanging fruit and tried to keep 418 pretty focused on that. I suspect more work can be done to optimize our types though which may include changing some owned values to references.

**Comment by howardjohn** [comment]
This is pretty much done, especially with Strng
