### ISSUE TITLE
Define API for ztunnel to display status of loaded secrets

### ISSUE THREAD

**Issue by GregHanson** [istio/ztunnel#166]
Similar to `istioctl proxy-config secrets`, define an API to display what certs ztunnel is attempting to use and the status for whether those certs are successfully loaded

**Comment by howardjohn** [comment]
Highly related https://github.com/istio/ztunnel/issues/276

**Comment by qfel** [comment]
Sorry, just got back from vacation. I'm mainly looking at a different issue, once I'm done with it I may look back here. But it's more of a side gig so may take a while - if somebody else wants to take it, feel free to.

**Comment by qfel** [comment]
So, I've looked around a bit. Few observations:
 - We seem to define traits and use generic types mostly for mocking, eg. CertificateProvider exists so that we can mock the gRPC client in tests
 - SecretManager also implements CertificateProvider, but it logically makes little sense, now that the API is evolving
 - SecretManager is "designed to be cheap to clone", but it's not clear what cloning a SecretManager logically means; the implicit assumption seems to be that it's really kind of a smart pointer to the real implementation that might not be cheap to clone, but then - use `Arc<SecretManager>`?
 - There's a bunch of code passing around `Box<dyn CertificateProvider>`, using Arc should be strictly better (since cloning the inner SecretManager involves cloning an Arc anyway)
 - The dyn part above isn't because we need different implementations of the SecretManager interface; rather, it's for mocking the underlying gRPC client

All that considered, what I want to do in preparation for plumbing the SecretManager to admin.rs is:
 - Remove the CertificateProvider trait
 - Convert uses of `Box<dyn CertificateProvider>` to `Arc<SecretManager>`
 - Remove the generic-ness of SecretManager and instead use `Box<dyn SomeCaClientTrait>` internally
 - Alternatively, we could construct lightweight gRPC servers in unit tests and use a real CaClient talking to a mock server on loopback (or via UDS), that would remove the need for abstracting the CaClient as a trait - but that's probably an overkill

Then, admin.rs can get `Arc<SecretManager>` that may or may not be based on a real gRPC client, and either way it can query the SecretManager for the list of certs (via a new method on SecretManager).

Does that make sense?

**Comment by GregHanson** [comment]
>Remove the CertificateProvider trait

@qfel matches with my findings as well.  To my understanding, SecretManager is the only resource that is actually keeping track of all the Identities a ztunnel knows about, making it much harder for other implementations of the CertificateProvider interface to provide a comprehensive dump

**Comment by GregHanson** [comment]
resolved by https://github.com/istio/ztunnel/pull/434
