### ISSUE TITLE
Consider using command arguments instead of environment variables

### ISSUE THREAD

**Issue by PiotrSikora** [istio/ztunnel#199]
There is already a lot of undocumented options, with somehow inconsistent syntax.

Could we convert them to command arguments or is there a reason why we're using environment variables?

**Comment by howardjohn** [comment]
The options now are definitely going to need to be reworked, but I don't think my args; we have intentionally avoided using args around Istio because they make it hard to modify in Kubernetes. https://github.com/istio/ztunnel/issues/7 has some details but needs to be fleshed out; likely we will use a configmap as the primary means of config (possibly with env var override)

**Comment by howardjohn** [comment]
We are now reading from configmap/env var, aligning with how istio is configured in other components
