### ISSUE TITLE
Enable building on arm64

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#35]
Currently, the build fails since we use the FIPS boringssl which only works on amd64.

Even with the FIPS disabled though, still getting issues around `poly_rq_mul.S` that we will need to resolve

**Comment by ilrudie** [comment]
I have an M2 Mac and could work on this

**Comment by digitalsanctum** [comment]
Isn't this a dupe of #1 ?

**Comment by ilrudie** [comment]
Could be. I have an intel mac I can try to confirm if its MacOS or M1/ARM that's the issue.

**Comment by ilrudie** [comment]
ARM could also be for something like graviton support not _just_ m1/macos as well

**Comment by stevenctl** [comment]
Allow developers using arm machines to contribute.
May also be required in some production environments.

**Comment by howardjohn** [comment]
https://github.com/istio/ztunnel/pull/139

**Comment by yuval-k** [comment]
we can also consider an approach similar to github.com/cloudflare/quiche, where we embed boring in this crate, so we don't need to set env vars for dependant crates (so that users won't need to remove the env vars manually, as specified in the readme)
https://github.com/cloudflare/quiche/blob/master/quiche/src/build.rs

**Comment by bleggett** [comment]
@yuval-k Thx for the hint - that strategy unfortunately doesn't work with `boring 2.1.0` - only with `2.0.0` that quiche uses, due to changes in `build.rs` for `boring-sys` which seem to break the ability to effectively vendor binaries: https://github.com/cloudflare/boring/blob/master/boring-sys/build.rs#L330

**Comment by bleggett** [comment]
Adding this as a ref - https://github.com/cloudflare/boring/pull/97 

A clang environmental dep might be easy to work around with a custom build image once that is - our current buildimage is too new for `clang-7`, which is what the pinned version of `boringssl` that `boring-sys` tries to autobuild (when installed as a Gitref dep) requires.

When that merges we should be good with `clang-12`, which is available for both arm64 and amd64 in our current build image, at least.
